### ISSUE TITLE
Automerge throws on credentials error

### ISSUE THREAD

**Issue by darthtrevino** [ridedott/merge-me-action#115]
**How would you describe the issue?**
I'm trying to use this workflow in a project of mine. The project has a protected master branch, and I'm seeing the following error in the run log. The run url is [here](https://github.com/microsoft/chart-parts/commit/1d35e72e682729bb8901dbba6136f885097e1bfa/checks?check_suite_id=324879869).  Additionally, the run is marked as successful even though the operation failed.

```
Run ridedott/dependabot-auto-merge-action@master
pullRequestHandle: PullRequestId: MDExOlB1bGxSZXF1ZXN0MzQ0NjY5OTc1, commitHeadline: build(deps): bump gatsby-plugin-typescript from 2.1.18 to 2.1.19.
##[warning]GraphqlError: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
##[warning]{"data":{"mergePullRequest":null},"errors":[{"type":"UNPROCESSABLE","path":["mergePullRequest"],"locations":[{"line":3,"column":5}],"message":"You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information."}],"name":"GraphqlError","request":{"query":"\n  mutation ($commitHeadline: String!, $pullRequestId: ID!) {\n    mergePullRequest(input: {commitBody: \"\", commitHeadline: $commitHeadline, mergeMethod: SQUASH, pullRequestId: $pullRequestId}) {\n      clientMutationId\n    }\n  }\n","variables":{"commitHeadline":"build(deps): bump gatsby-plugin-typescript from 2.1.18 to 2.1.19","pullRequestId":"MDExOlB1bGxSZXF1ZXN0MzQ0NjY5OTc1"}}}
```

**Comment by darthtrevino** [comment]
In my case I needed to create a Personal Access Token to get this to work

**Comment by merlinnot** [comment]
Hi. Yes, you need to either use a PAT of an administrative user, or adjust your branch protection rules so that one approval is sufficient to merge. That's why the Action also approves your PR. It's a limitation of GitHub which we're monitoring and we'll adjust the Readme once it's resolved.

I'll keep this issue open until this is fixed.
