### ISSUE TITLE
Allowing auto-merge on other kind of bots

### ISSUE THREAD

**Issue by qcastel** [ridedott/merge-me-action#133]
**What do you want to achieve?**

I got a bot to do my release and do auto-backporting.
It would be nice to be able to specify another kind of bot, that we allow the PR to be automerged.

**What is the current way of working?**

I just do it manually

**How much does it hurt?**

Not much, I just like automatised what is possible :)

**Comment by qcastel** [comment]
Seems like if this constant: https://github.com/ridedott/dependabot-auto-merge-action/blob/master/src/constants.ts
was instead the default value of a github action input, that would do the job.

**Comment by merlinnot** [comment]
That sounds like a good idea to make it more generic. We could use an input to specify login names for which auto-merge should happen. Would you be willing to make a PR for that?

**Comment by merlinnot** [comment]
Fixed as of v1.1.0, see https://github.com/ridedott/merge-me-action#enable-auto-merge-for-a-different-bot
