### ISSUE TITLE
Auto Merge fails on initial try

### ISSUE THREAD

**Issue by Twonki** [ridedott/merge-me-action#241]
The action runs on checksuite-success. It retries three times and fails on each. 
Doing a `dependabot recreate` triggers automerge correctly, and the rebasing of other open dependabot prs closes other PRs successfully too. 

It fails on with the following error message: 
```
Run ridedott/dependabot-auto-merge-action@master
Found pull request information: {"reviewEdges":[{"node":{"state":"APPROVED"}}]}.
##[error]An unexpected error occurred: (e || "").replace is not a function, TypeError: (e || "").replace is not a function
    at escapeData (evalmachine.<anonymous>:1:65447)
    at Command.toString (evalmachine.<anonymous>:1:65373)
    at issueCommand (evalmachine.<anonymous>:1:64866)
    at Object.issue (evalmachine.<anonymous>:1:64935)
    at Object.error (evalmachine.<anonymous>:1:91320)
    at Object.t.pullRequestHandle (evalmachine.<anonymous>:1:117513)
    at processTicksAndRejections (internal/process/task_queues.js:93:5).
##[error]Node run failed with exit code 1
```

**What are the expected results?**

It should work on initial try. 

**What are the actual results?**

PRs are not properly merged on the initial try, but the Checksuite is all green. It retries 3 times and then fails. 
Rebasing or recreating the PR with `dependabot recreate` in chat resolves the issue as shown in the pr example below. 

**How much does it hurt?**

Telling Dependabot to recreate takes as long as merging with admin privileges. Therefore the action does not smooth anything when this bug occurs. 

**Further Links:**

[An example failing Action](https://github.com/Twonki/Microtope/pull/362/checks?check_run_id=412200710) and the corresponding failing [example PR](https://github.com/Twonki/Microtope/pull/362). 

The [Action YML](https://github.com/Twonki/Microtope/blob/master/.github/workflows/dependabot_automerge.yml) Is the default.

**Comment by Twonki** [comment]
Small edit: 
The action was not on the default! 

I altered 
```yaml
...
uses: ridedott/dependabot-auto-merge-action@master
```
 to 
```yaml
...
uses: ridedott/merge-me-action@master
```

Link in initial Issue is the updated version. 

Will feedback probably ~tomorrow if it persists. 

Sneaky change of you. :shipit:

**Comment by merlinnot** [comment]
We're in the process of fixing the error. The error is actually a bug in a way we log errors... So once this is fixed, it should display more useful information on what goes wrong and we can keep working from there.

**Comment by merlinnot** [comment]
@Twonki @nuria-fl @hiwelo I merged two PRs: fix to the logging mechanism and better setup/configuration instructions (see the Readme). Let me know what the results are.

**Comment by merlinnot** [comment]
I'll go ahead and close this issue. Most likely you'll now see a different error message than originally reported, so it's probably the best to open a new issue for it.

**Comment by Twonki** [comment]
Just wanted to confirm that the issue seems to be resolved. 

Thank you very much for the quick fix :)
