### ISSUE TITLE
Pull request not created by dependabot, skipping.

### ISSUE THREAD

**Issue by z0rc** [ridedott/merge-me-action#451]
**How would you describe the issue?**

Hi,

I'm migrating from `dependabot-preview` to `dependabot`, see https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/. Github integrated `depandabot` is missing automerge feature, which was available in preview. Therefor I opted to use this github action to automerge dependabot PR's. Unfortunately it isn't working as expected.

**How can we reproduce the issue?**

* Configure new dependabot for repo. For example this is how I did https://github.com/z0rc/dotfiles/blob/master/.github/dependabot.yml.
* Enable merge-me for dependabot user. I did it like this https://github.com/z0rc/dotfiles/blob/master/.github/workflows/automerge.yml.
* Observe merge-me action, for example here https://github.com/z0rc/dotfiles/runs/760276753?check_suite_focus=true.

**What are the expected results?**

merge-me action would recognize configured `GITHUB_LOGIN: dependabot` and merge the PR.

**What are the actual results?**

merge-me action doesn't recognize `dependabot` "user" configured via `GITHUB_LOGIN`. `Pull request not created by dependabot, skipping.`

**How much does it hurt?**

Dependabot migration caught me off guard and I have to manually merge couple of PR's from it manually each day,

**Comment by mad-it** [comment]
It looks like the people at GitHub pulled a big woopsy. The app name is indeed `dependabot` and no longer `dependabot-preview`. But under the hood its still called `dependabot-preview`.

Im pretty sure removing `GITHUB_LOGIN` would solve your issue as it would default back to `dependabot-preview[bot]`.

**Comment by z0rc** [comment]
Thanks. I updated the action config and will report back once after it's run.

**Comment by merlinnot** [comment]
@z0rc We've changed this error message to be more descriptive, so that it helps our users find the right setting. If you'll need any more support from us, please feel free to reopen the issue!

**Comment by z0rc** [comment]
Just an update. I managed to get it working. Thanks to #452 I was able to find the right option `GITHUB_LOGIN: 'dependabot[bot]'`.
