### ISSUE TITLE
Filter PR to auto merge with semantic version

### ISSUE THREAD

**Issue by jraoult** [ridedott/merge-me-action#459]
**What do you want to achieve?**

GitHub is encouraging people to move to [Github-native dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview). As you know they removed auto-merge function.

With dependabot preview we are using NPM semantic versioning so that it only auto-merges minors and patches version, leaving major versions alone. It leaves us the opportunity to review (and learn) about major changes in the library (even if they don't break the tests) while making it as low maintenance as possible for other upgrades. We can arrive in the morning and all the _safe/easy_ upgrades are done.

This is our current setting in dependabot-preview:

<kbd>
<img src=https://user-images.githubusercontent.com/2046871/85523121-79eb3600-b5fe-11ea-90c0-63d744716ed5.png>
</kbd>

I think it is not possible to do this right now with _merge-me-action_ (and maybe it is just too hard to implement).

**What is the current way of working?**

Using the tandem Github-native dependabot we are either forced to auto-merge everything with _merge-me-action_ or manually merge all upgrades PR.

**How much does it hurt?**
It is unsustainable for us, so, for now, we plan to stay as long as possible on dependabot-preview.

**Comment by merlinnot** [comment]
Thank you for the feature request. We'll discuss it with the team by the end of the week if/when are we willing to pick it up ourselves and get back to you. In the meantime, we'll definitely accept a contribution!

**Comment by jraoult** [comment]
@merlinnot thx for coming back.

 _dependabot_ is not offering a standardized way to access the semver so I thought about parsing the PR's _title_. It seems very fragile though because there is a risk they change the format of the _title_ string.

I now think dependabot should tag the PR with either major/minor or patch and then it would just be a case of filtering by tag. _dependabot_ already have this information. So I don't know how much leverage you have with the dependabot team but it might be a thing to advocate for.

**Comment by merlinnot** [comment]
We have no leverage on GitHub 🙂 Parsing a title would be fragile indeed, but if we want to ship it, we have to rely on available information.

**Comment by jraoult** [comment]
@merlinnot I just posted feedback here https://support.github.com/contact/feedback?contact%5Bsubject%5D=Dependabot+Beta&contact%5Bcategory%5D=security asking about a tag with the upgrade level. I have very little hope for it to have any effect but I would have tried.

**Comment by jraoult** [comment]
So thankful for this 🙏  As expected my attempt to get in contact with GitHub was unfruitful so this is nice to see this implemented here.

**Comment by dunyakirkali** [comment]
@jraoult please let us know if it works for you as expected
