### ISSUE TITLE
Error on running action

### ISSUE THREAD

**Issue by sbrunner** [ridedott/merge-me-action#471]
**How would you describe the issue?**

From little time ago I get the following error:
```
Automatic merges enabled for GitHub login: dependabot-preview[bot].
Found pull request information: {"reviewEdges":[]}.
##[warning]MERGE_METHOD value input is ignored because its malformed, defaulting to SQUASH.
##[error]GraphqlError: 2 of 2 required status checks have not succeeded: 1 expected.
```

I suspect this dependency update: 
https://github.com/ridedott/merge-me-action/commit/d9046acb40d33a7dc5ae33423b403bac58a5264b

**How can we reproduce the issue?**

Used workflow:
https://github.com/camptocamp/ngeo/blob/master/.github/workflows/dependabot-auto-merge.yaml

**What are the expected results?**

Validate the PR

**What are the actual results?**

Error in workflow

**How much does it hurt?**

The action doesn't work anymore...

**Comment by mad-it** [comment]
Thanks for reporting. We will investigate this.

**Comment by merlinnot** [comment]
We've just fixed the bug. The error message will now contain more helpful information on why a merge action can't be performed.

**Comment by sbrunner** [comment]
Thanks :-)
