### ISSUE TITLE
README is a little lacking in basic explanation

### ISSUE THREAD

**Issue by rjmunro** [ridedott/merge-me-action#560]
I think this project gives something like GitLab's "Merge when CI completes" checkbox functionality in GitHub, but it's not clear from the README, which just dives into how to configure the action for 3 different scenarios. It should have an opening sentence, something like:

> This action will automatically merge PRs when all the other actions have passed and there are no merge conflicts. It provides similar functionality to GitLab's "Merge when CI completes" checkbox.

If the above is what this action does, I'd really like to use it on my projects. 😃

**Comment by merlinnot** [comment]
Thanks for the feedback, you're probably right, we should focus a little more on users who just discovered the Action. I created a PR to fix it, let me know if it's clear enough.
