### ISSUE TITLE
Retry on mergeableState: UNKNOWN

### ISSUE THREAD

**Issue by joroKr21** [ridedott/merge-me-action#674]
**How would you describe the issue?**

We have a bot that updates dependencies once a week and it creates PRs in quick succession.
Once the first PR is merged automatically, other PRs see `mergeableState: UNKNOWN` for a short while.
Sometimes you can even observe that in the GitHub UI (the merge button is greyed out).
We tried increasing the `MAXIMUM_RETRIES`, but it looks like the action is not retrying in this case.

**How can we reproduce the issue?**

I'm not sure if it can be reproduced manually without a bot.
But basically create multiple PRs in quick succession.
Here is an example run: https://github.com/moia-dev/scynamo/runs/1548816898#step:2:7

**What are the expected results?**

Retry on `mergeableState: UNKNOWN` according to the `MAXIMUM_RETRIES` setting.

**What are the actual results?**

AFAICT there were no retries in that run.

**How much does it hurt?**

Unfortunately this problem breaks our use case.

**Comment by z0rc** [comment]
I've got hit with same issue in recent week, 2/3 merge requests from dependabot fail to merge with `Pull request is not in a mergeable state: UNKNOWN.`, for example here https://github.com/z0rc/dotfiles/pull/2520/checks?check_run_id=1932884792#step:2:11.

**Comment by desbo** [comment]
I'm experiencing this too. I can see that the retry logic is only applied when attempting to merge the PR, which doesn't happen with `mergeableState: UNKNOWN`. [According to GitHub](https://docs.github.com/en/graphql/reference/enums#mergeablestate) this state means that the mergability is still being determined, so it'd probably make sense to include this in the retry.

**Comment by desbo** [comment]
I've found that the `UNKNOWN` state is reported when the workflow run for a PR is in progress. As this action runs as part of a workflow run, it seems the PR will always be in this state when the automated merge is attempted. So rather than adding retry logic (which would only extend the runtime of the action), I think merges should still be attempted on state `UNKNOWN`. 

If it helps anyone, I ended up making my own action to merge PRs that doesn't have this issue: https://github.com/desbo/merge-pr-action

**Comment by xtazz** [comment]
@z0rc @desbo @joroKr21 let us know if it helped to resolve the issue

**Comment by desbo** [comment]
@xtazz based on my above comment, I suspect this will only serve to make the action run for the full retry duration before falling, as the `unknown` state is reported when a workflow run is in progress. I haven’t tested it though.

**Comment by joroKr21** [comment]
> I suspect this will only serve to make the action run for the full retry duration before falling, as the unknown state is reported when a workflow run is in progress.

But then how does it succeed on the first PR? 🤔

**Comment by desbo** [comment]
Not sure. Some clarity from GH on what the unknown state actually represents would be helpful, I guess.

**Comment by xtazz** [comment]
@desbo  I found a comment from GitHub: 
> The null value means that the mergeability of the pull request hasn't been computed yet. Mergeability is computed on demand and in the background, so when you fetch a pull request for which the mergeability isn't known -- you get back a null value but also a job is kicked off to compute the mergeability. If you make another request, you should see a non-null value for the mergeable attribute.

So, sometimes it will be already calculated and present, but sometimes `merge-me` action will kick it off, that's why I implemented retry logic for getting PR information.
