### ISSUE TITLE
False negative runs against dependabot PRs

### ISSUE THREAD

**Issue by daneden** [ridedott/merge-me-action#866]
Hi there! I recently installed this action on a couple of my repos and noticed that the action fails to correctly recognise PRs opened by dependabot. I believe there’s a bug in this line:

https://github.com/ridedott/merge-me-action/blob/bf7c57bfa6b302a5c7d0849351809e8721ae6bcd/src/common/merge.ts#L146

`commitAuthorName` should be updated to `authorLogin`; in my case, `commitAuthorName` is logged as `Daniel Eden` (my name), whereas `authorName` is logged as `dependabot` (the allowed merge username). See [this run log](https://github.com/Lucid-Toys/underground.lucid.toys/runs/2322571687?check_suite_focus=true) for details.

**Comment by joachimroeleveld** [comment]
Hi @daneden this should be [resolved](https://github.com/ridedott/merge-me-action/pull/861) with the latest release. Could you confirm this fixed the issue for you?

**Comment by daneden** [comment]
Hey @joachimroeleveld! I’m not sure if I’m just doing it wrong, but [my workflow](https://github.com/Lucid-Toys/underground.lucid.toys/blob/main/.github/workflows/merge-dependabot-prs.yaml) doesn’t seem to be running on `check_suite`. Here’s [an example PR](https://github.com/Lucid-Toys/underground.lucid.toys/pull/452). My expectation would be that when a PR is opened by Dependabot and the required checks (E2E/cypress and Vercel preview deployment) pass, the PR would be merged by your action, but it doesn’t seem to be working.

**Comment by joachimroeleveld** [comment]
@daneden `check_suite` should be used for CIs other than Github Actions. We should probably change the README to reflect that. Changing it to `workflow_run` should make it work.

**Comment by daneden** [comment]
Ah I see; thanks for clarifying. I wonder why the Vercel integration doesn’t trigger `check_suite` 🤔 either way, I think I can work around this by enabling auto-merge for dependabot pull requests, which I can [build an action for](https://github.com/daneden/enable-automerge-action).
