### ISSUE TITLE
Not recognizing GitHub-native dependabot

### ISSUE THREAD

**Issue by amclin** [ridedott/merge-me-action#994]
**How would you describe the issue?**
The preset `DEPENDABOT_MINOR` doesn't appear to work with the new GitHub-native Dependabot. (The old dependabot will be turned off in early August). The logs indicate Dependabot was not recognized.

**How can we reproduce the issue?**

1. Enable GitHub native dependabot
2. Setup a workflow to automerge:
    * https://github.com/amclin/advent-of-code/blob/master/.github/workflows/automerge.yml#L16
3. Update a Dependabot-created branch to trigger the workflow

**What are the expected results?**

Dependabot-created PR merges

**What are the actual results?**
Dependabot-created PR does not merge. Log indicates Dependabot was not detected by merge-me-action
```
Run ridedott/merge-me-action@v2
  with:
    GITHUB_TOKEN: ***
    PRESET: DEPENDABOT_MINOR
    GITHUB_LOGIN: dependabot
    MERGE_METHOD: SQUASH
    ENABLED_FOR_MANUAL_CHANGES: false
    MAXIMUM_RETRIES: 3
Automatic merges enabled for GitHub login: dependabot.
Found pull request information: {"authorLogin":"dependabot","commitMessage":"Merge branch 'master' into dependabot/npm_and_yarn/mocha-9.0.2","commitMessageHeadline":"Merge branch 'master' into dependabot/npm_and_yarn/mocha-9.0.2","mergeableState":"MERGEABLE","merged":false,"pullRequestId":"MDExOlB1bGxSZXF1ZXN0NjgzNjgyMzQ4","pullRequestNumber":179,"pullRequestState":"OPEN","pullRequestTitle":"chore(deps-dev): bump mocha from 9.0.1 to 9.0.2","repositoryName":"advent-of-code","repositoryOwner":"amclin","reviewEdges":[]}.
Pull request changes were not made by dependabot.
```

**How much does it hurt?**

A lot, especially come August when legacy Dependabot goes away without a reliable automerge solution.

**Comment by merlinnot** [comment]
Hi! I looked into latest executions of the action in the repository you linked and I see [this message](https://github.com/amclin/advent-of-code/runs/3022457474?check_suite_focus=true#step:2:11):

> Pull request changes were not made by dependabot.

Looking at the [PR](https://github.com/amclin/advent-of-code/pull/179), I can see that you merged `master` branch into this PR. In this case, by default, the action will not merge the PR - details of this behavior are documented here: https://github.com/ridedott/merge-me-action#enable-for-manual-changes.

Good news - it's configurable! So if you don't like the default behavior, you can enable an option to merge PRs with manual changes.

Let me know if this addresses your use case.

**Comment by amclin** [comment]
@merlinnot thanks for the fast response and looking into it! I merged `master` into the branch to update the dependabot-opened PR. That's going to be a pretty typical scenario for keeping a branch fresh, is there a reason it's not defaulted to on?

Alternatively, I had Dependabot recreate with `@dependabot recreate` (instead of the merge approach of keeping up to date) and that seems to have worked.

**Comment by merlinnot** [comment]
We can't guarantee/detect if changes in the merge commit are "automatic". Theoretically developers can put any changes in such a merge commit, including malicious code.
